params:
  objective: "regression"
  metric: "rmse"
  num_leaves: 100
  max_depth: 10
  feature_fraction: 0.8
  subsample_freq: 1
  bagging_fraction: 0.95
  learning_rate: 0.1
  boosting: "gbdt"
  lambda_l1: 0.1
  lambda_l2: 10
  random_state: 42
  verbosity: -1
